### ISSUE TITLE
Lack of documentation.

### ISSUE THREAD

**Issue by ghost** [bigbluebutton-bot/bbb-translation-bot#9]
Everything is up and running, but what to do next? no info about how to add it to the bbb.
Should bot join the room, or some button should appear? who knows.

**Comment by fvlasie** [comment]
Did you ever figure this out?

**Comment by JulianKropp** [comment]
A new room is created and the link to join it will be printed in the logs of the bot. The closed captions functionality will be enabled by the bot. You just have to press the CC button on the bottom left of the meeting.
